language: python
sudo: required
dist: trusty
python:
  - 3.5
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py34
  - TOXENV=py35
install: pip install -q tox
script: tox
notifications:
  email: false
