language: python
sudo: required
dist: trusty
matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=py34
      python: 3.4
    - env: TOXENV=py35
      python: 3.5
    - env: TOXENV=py36
      python: 3.6
    - env: TOXENV=pypy
      python: pypy
    - env: TOXENV=pep8
install: pip install -q tox
script: tox
deploy:
  provider: pypi
  user: tim
  distributions: sdist bdist_wheel
  password:
    secure: oi6C6PX090a99j+oskFPjjX0WQ2PhvhreXC9RzplRDKXWXSyGptHzJb6U6WLIFVk6VBcvQRB6U429slPCpto/Va4oYdtw6J3BLp8S2SMU/XboHeZkXhlJPf3WeQ/KaWJzeHAKhWb9wpuv9E5a/WTyKgHn0XkJX0q0s9faDYd1Z0=
  on:
    tags: true
    repo: cyberdelia/metrology
    condition: "$TOXENV = py27"
notifications:
  email: false
