language: python
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=py34
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-4.7
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 20
install: pip install -q --use-mirrors tox
script: tox
